/* Basic Modeling

LIVROS

NOME EDITORA - VARCHAR 30
VALOR LIVRO - FLOAT
NOME AUTOR - VARCHAR 30
SEXO AUTOR - CHAR 1
UF EDITORA - CHAR 2
NOME LIVRO - VARCHAR 30
NUMERO PAGINAS - INTEGER
*/

/* Creating the database */

CREATE DATABASE EXERCICIO;

/* Conecting to the base */

USE EXERCICIO;

/* Creating tables */

CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NOME_AUTOR VARCHAR(30),
	SEXO_AUTOR CHAR(1),
	NUMERO_PAGINAS INT(4),
	NOME_EDITORA VARCHAR(30),
	VALOR_LIVRO FLOAT(6,2),
	UF_EDITORA CHAR(2),
	ANO_LIVRO INT(4)
);

/* Showing tables */

SHOW TABLES;

/* Showing table description */

DESC LIVROS;