/* Counting rows on a table */

SELECT COUNT(*)
FROM LIVROS;

SELECT COUNT(*) AS 'QUANTIDADE'
FROM LIVROS
WHERE NOME_AUTOR LIKE 'C%';

SELECT UF_EDITORA AS 'UF', COUNT(*) AS 'QUANTIDADE'
FROM LIVROS
WHERE UF_EDITORA = 'SP';

/* Counting using GROUP BY */

SELECT SEXO_AUTOR AS SEXO, COUNT(*) AS 'QUANTIDADE'
FROM LIVROS
GROUP BY SEXO_AUTOR;

SELECT UF_EDITORA AS UF, COUNT(*) AS 'QUANTIDADE'
FROM LIVROS
GROUP BY UF_EDITORA;

SELECT COUNT(*) AS 'QUANTIDADE', SEXO_AUTOR AS 'SEXO', ANO_LIVRO AS 'ANO'
FROM LIVROS
WHERE ANO_LIVRO = 2018
GROUP BY SEXO_AUTOR;

SELECT UF_EDITORA AS 'UF', COUNT(*) AS 'QUANTIDADE'
FROM LIVROS
WHERE UF_EDITORA = 'SP'
OR UF_EDITORA = 'RJ'
GROUP BY UF_EDITORA;
