CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNOS(
	NUMERO INT,
	NOME VARCHAR(30)
);

INSERT INTO ALUNOS VALUES(1,'JOAO');
INSERT INTO ALUNOS VALUES(1,'MARIA');
INSERT INTO ALUNOS VALUES(2,'ZOE');
INSERT INTO ALUNOS VALUES(2,'ANDRE');
INSERT INTO ALUNOS VALUES(3,'CLARA');
INSERT INTO ALUNOS VALUES(1,'CLARA');
INSERT INTO ALUNOS VALUES(4,'MAFRA');
INSERT INTO ALUNOS VALUES(5,'JANAINA');
INSERT INTO ALUNOS VALUES(1,'JANAINA');
INSERT INTO ALUNOS VALUES(3,'MARCELO');
INSERT INTO ALUNOS VALUES(4,'GIOVANI');
INSERT INTO ALUNOS VALUES(5,'ANTONIO');
INSERT INTO ALUNOS VALUES(6,'ANA');
INSERT INTO ALUNOS VALUES(6,'VIVIANE'); 

SELECT NUMERO, NOME FROM ALUNOS
ORDER BY NUMERO;

SELECT NUMERO, NOME FROM ALUNOS
ORDER BY 1;

SELECT NUMERO, NOME FROM ALUNOS
ORDER BY 2;

SELECT NUMERO, NOME FROM ALUNOS
ORDER BY NUMERO, NOME;

SELECT NUMERO, NOME FROM ALUNOS
ORDER BY NUMERO, NOME DESC;

SELECT NUMERO, NOME FROM ALUNOS
ORDER BY NUMERO DESC, NOME DESC;

SELECT NUMERO, NOME FROM ALUNOS
ORDER BY 1, 2;

SELECT NOME FROM ALUNOS --Only if you put the column names on the 'order by'
ORDER BY NUMERO, NOME;
